name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: ['**']

permissions: {}

jobs:
  lint-actions:
    name: GitHub Actions audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0
        with:
          advanced-security: false

  tests:
    runs-on: ubuntu-latest
    name: Linter
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.8
      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: Lint YAML files
        run: yamllint gems rubies
      - name: Set up Ruby
        uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          ruby-version: 4.0
      - name: Install ruby dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Validate YAML
        run: bundle exec rake lint
